// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image_full: dynamic(() => import("./ImageFull")),
  image_grid: dynamic(() => import("./ImageGrid")),
  paragraph: dynamic(() => import("./Paragraph")),
  video: dynamic(() => import("./Video")),
};
